name: Static Analysis
on:
  pull_request: { }
  push:
    branches: [ develop, master ]
jobs:
  ts_lint:
    name: "Typescript Syntax Check"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          cache: 'yarn'

      # Does not need branch matching as only analyses this layer
      - name: Install Deps
        run: "yarn install --pure-lockfile"

      - name: Typecheck
        run: "yarn run lint:types"

  i18n_lint:
    name: "i18n Check"
    uses: matrix-org/matrix-react-sdk/.github/workflows/i18n_check.yml@develop

  js_lint:
    name: "ESLint"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          cache: 'yarn'

      # Does not need branch matching as only analyses this layer
      - name: Install Deps
        run: "yarn install --pure-lockfile"

      - name: Run Linter
        run: "yarn run lint:js"

  tsc-strict:
    name: Typescript Strict Error Checker
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
      checks: write
    steps:
      - uses: actions/checkout@v3

      - name: Get diff lines
        id: diff
        uses: Equip-Collaboration/diff-line-numbers@v1.0.0
        with:
          include: '["\\.tsx?$"]'

      - name: Detecting files changed
        id: files
        uses: futuratrepadeira/changed-files@v3.2.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pattern: '^.*\.tsx?$'

      - uses: t3chguy/typescript-check-action@main
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          use-check: false
          check-fail-mode: added
          output-behaviour: annotate
          ts-extra-args: '--strict'
          files-changed: ${{ steps.files.outputs.files_updated }}
          files-added: ${{ steps.files.outputs.files_created }}
          files-deleted: ${{ steps.files.outputs.files_deleted }}
          line-numbers: ${{ steps.diff.outputs.lineNumbers }}
