name: Build

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [17.x]
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build Ubuntu
      run: |
        yarn install
        yarn run fetch --noverify --cfgdir config
        yarn run build

    - name: Build Windows
      run: yarn run build:64
    
    - name: Archive mapping
      uses: actions/upload-artifact@v2
      with:
        name: Builds
        path: /dist